# Aaron Gensetter M300

# DB server has to start before Web Server!

# TODO: check to start data server before nextcloud???

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64" # Ubuntu 20.04

  # Define Box 1 (DB Server)
  config.vm.define "box1" do |box1|
    box1.vm.provider "virtualbox" do |vb|
      vb.name = "M300-box1-DBS"
      vb.memory = 3072
      vb.cpus = 2
    end
    box1.vm.hostname = "box1"
    box1.vm.network "private_network", ip: "10.9.8.11"
    box1.vm.network "forwarded_port", guest:3306, host:3306, auto_correct: true
    box1.vm.provision "shell", path: "box1/script.sh" # install script
  end # end box 1

  # Define Box 2 (Data Server)
  config.vm.define "box2" do |box2|
    box2.vm.provider "virtualbox" do |vb|
      vb.name = "M300-box2-DAT"
      vb.memory = 1024
      vb.cpus = 1
    end
    box2.vm.hostname = "box2"
    box2.vm.network "private_network", ip: "10.9.8.12"
    box2.vm.provision "shell", path: "box2/script.sh" # install script
  end # end box 2

  # Define Box 3 (Apache2 Webserver)
  config.vm.define "box3" do |box3|
    box3.vm.provider "virtualbox" do |vb|
      vb.name = "M300-box3-WEB"
      vb.memory = 3072
      vb.cpus = 2
    end
    #box3.vm.synced_folder "./box3/data", "/var/www/html"
    box3.vm.hostname = "box3"
    box3.vm.network "private_network", ip: "10.9.8.13"
    box3.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true # forward port 80 to 8080
    box3.vm.network "forwarded_port", guest:443, host:8443, auto_correct: true # forward port 443 to 8443
    box3.vm.provision "shell", path: "box3/script.sh" # install script
  end # end box 3

  # Define Box 4 (Reverse proxy Server) ? need ?
  config.vm.define "box4" do |box4|
    box4.vm.provider "virtualbox" do |vb|
      vb.name = "M300-box4-RVP"
      vb.memory = 1024
      vb.cpus = 1
    end
    box4.vm.hostname = "box4"
    box4.vm.network "private_network", ip: "10.9.8.14"
    box4.vm.provision "shell", path: "box4/script.sh" # install script
  end # end box 4

end # end script
